### ISSUE TITLE
application crash on start

### ISSUE THREAD

**Issue by pitersky** [enricostara/termgram#11]
The log is follows:

```
 T E R M G R A M  0.2.1
powered by telegram.link

Welcome to TERMGRAM, a terminal client to connect with Telegram.

Termgram Login
Username (<cut>): 
Password: ****

Welcome back <cut>!
start updates
set state { T:api.type.updates.State, pts: 671, qts: 0, date: 1453223759, seq: 2, unread_count: 0 }

________________________________________

    Chats:

    [ 8 ] <cut>  
        <cut>

    [ 7 ] <cut>
        <cut>

    [ 6 ] <cut>
        <cut>

selectChat error:  Error: Unknown user type api.type.UserSelf
    at retrieveInputPeer (/home/username/.npm-packages/lib/node_modules/termgram/lib/use-case/select-chat.js:98:15)
    at renderChat (/home/username/.npm-packages/lib/node_modules/termgram/lib/use-case/select-chat.js:73:21)
    at /home/username/.npm-packages/lib/node_modules/termgram/lib/use-case/select-chat.js:32:44
    at lib$es6$promise$$internal$$tryCatch (/home/username/.npm-packages/lib/node_modules/termgram/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/home/username/.npm-packages/lib/node_modules/termgram/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (/home/username/.npm-packages/lib/node_modules/termgram/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (/home/username/.npm-packages/lib/node_modules/termgram/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
stop updates

```

I notice "api.type.UserSelf", maybe application crashes because i have added myself to telegram user lst? Don't really know, just guessing.

Cheers

P.S. theese numbers can be helpful also

node -v
v5.4.1

npm -v
3.5.3

**Comment by Pro-Ton** [comment]
Same problem here... :(

```
 T E R M G R A M  0.2.1
powered by telegram.link

Welcome to TERMGRAM, a terminal client to connect with Telegram.

Termgram Login
Username: edge
Password: 1234

Welcome back edge!
start updates
set state { T:api.type.updates.State, pts: 12200, qts: 0, date: 1477161379, seq: 1, unread_count: 0 }

________________________________________

        Chats:

        [ 16 ] Telegram Store Bot
                History was cleared.

selectChat error:  Error: Unknown user type api.type.UserSelf
    at retrieveInputPeer (C:\Users\edge\AppData\Roaming\npm\node_modules\termgram\lib\use-case\select-chat.js:98:15)
    at renderChat (C:\Users\edge\AppData\Roaming\npm\node_modules\termgram\lib\use-case\select-chat.js:73:21)
    at C:\Users\edge\AppData\Roaming\npm\node_modules\termgram\lib\use-case\select-chat.js:32:44
    at lib$es6$promise$$internal$$tryCatch (C:\Users\edge\AppData\Roaming\npm\node_modules\termgram\node_modules\telegram.link\node_modules\es6-promise\dist\es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (C:\Users\edge\AppData\Roaming\npm\node_modules\termgram\node_modules\telegram.link\node_modules\es6-promise\dist\es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (C:\Users\edge\AppData\Roaming\npm\node_modules\termgram\node_modules\telegram.link\node_modules\es6-promise\dist\es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (C:\Users\edge\AppData\Roaming\npm\node_modules\termgram\node_modules\telegram.link\node_modules\es6-promise\dist\es6-promise.js:125:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
stop updates


```

Any suggestions?
