### ISSUE TITLE
Couldn't start termgram

### ISSUE THREAD

**Issue by err4o4** [enricostara/termgram#2]
When I try to start termgram I'm getting these error

```
/usr/local/lib/node_modules/termgram/lib/user-interface.js:17
    return new Promise(function (fulfill) {
               ^
ReferenceError: Promise is not defined
    at Object.askWordInput (/usr/local/lib/node_modules/termgram/lib/user-interface.js:17:16)
    at askUsername (/usr/local/lib/node_modules/termgram/lib/use-case/sign-up.js:51:8)
    at signUp (/usr/local/lib/node_modules/termgram/lib/use-case/sign-up.js:25:5)
    at main (/usr/local/lib/node_modules/termgram/termgram.js:32:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/termgram/termgram.js:60:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by enricostara** [comment]
see closed [issue#1](https://github.com/enricostara/termgram/issues/1)
