### ISSUE TITLE
client.sendCodeToPhone undefined

### ISSUE THREAD

**Issue by superbarne** [enricostara/termgram#8]
I got this error when i enter my telephone number:

/usr/local/lib/node_modules/termgram/lib/client-proxy.js:73
                            client.sendCodeToPhone(phoneNumber, fulfill);
                                   ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/termgram/lib/client-proxy.js:73:36
    at Client.<anonymous> (/usr/local/lib/node_modules/termgram/lib/client-proxy.js:132:13)
    at Client.g (events.js:199:16)
    at Client.emit (events.js:104:17)
    at null._onTimeout (/usr/local/lib/node_modules/termgram/node_modules/telegram.link/lib/utility.js:44:26)
    at Timer.listOnTimeout (timers.js:110:15)

**Comment by superbarne** [comment]
wrong nodejs version...
