### ISSUE TITLE
client.sendCodeToPhone fails with TypeError: undefined is not a function

### ISSUE THREAD

**Issue by 0x15** [enricostara/termgram#9]
This looks like the same issue as #8, but I am using NodeJS version 0.12.7, which should be supported (?)

```
Provide your phone number in order to receive the verification code from Telegram
Phone number, must have the international code: +xxxxxxxxxxx
/usr/local/lib/node_modules/termgram/lib/client-proxy.js:73
                            client.sendCodeToPhone(phoneNumber, fulfill);
                                   ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/termgram/lib/client-proxy.js:73:36
    at Client.<anonymous> (/usr/local/lib/node_modules/termgram/lib/client-proxy.js:124:13)
    at Client.g (events.js:199:16)
    at Client.emit (events.js:104:17)
    at null._onTimeout (/usr/local/lib/node_modules/termgram/node_modules/telegram.link/lib/utility.js:58:26)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by enricostara** [comment]
Please, try to update the project to the last version and let me know. Consider anyway this example application not yet stable and complete.

**Comment by fazo96** [comment]
Hello, I really love that you're building a node library and a command line client for telegram!

I'm trying to run termgram, but I have the same problem as @0x15:

```
Provide your phone number in order to receive the verification code from Telegram
Phone number, must have the international code: +39xxxxxxxxxx
/home/fazo/.npm_prefix/lib/node_modules/termgram/lib/client-proxy.js:75
                            client.sendCodeToPhone(phoneNumber, fulfill);
                                   ^
TypeError: undefined is not a function
    at /home/fazo/.npm_prefix/lib/node_modules/termgram/lib/client-proxy.js:75:36
    at Client.<anonymous> (/home/fazo/.npm_prefix/lib/node_modules/termgram/lib/client-proxy.js:126:13)
    at Client.g (events.js:199:16)
    at Client.emit (events.js:104:17)
    at null._onTimeout (/home/fazo/.npm_prefix/lib/node_modules/termgram/node_modules/telegram.link/lib/utility.js:58:26)
    at Timer.listOnTimeout (timers.js:119:15)

```

This was obtained by cloning the repo, `npm install -g` the code directly from master and running `termgram`. I got the same error by downloading the latest release from npm.

**Comment by tomcpc** [comment]
I can't get past the phone number request as well. I get either the message saying it is not an international number, or I get stuck with an " undefined '+55xxxxxxxxxx' ".

**Comment by fazo96** [comment]
@tomcpc I'm sorry, I tried to fix termgram but it didn't work out. If you want to see a working client, try [my own](http://github.com/fazo96/telecommander)
